---
title: "AbsenteeismAtWork"
author: "Yongye Tan"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
# import libraries
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r readTheFile}
# read the file using the absolute path of my file
# https://www.kaggle.com/datasets/kewagbln/absenteeism-at-work-uci-ml-repositiory
# https://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work
absent <- read.csv(file = "/Users/yongyetan/Desktop/Area51/AbsenteeismAtWork/Absenteeism_at_work.csv", sep = ";")
absent
```
```{r exploratry}
# data clean up to see if there is any NA's
summary(absent)
```




```{r}
absent %>% 
  group_by(Age) %>% 
  summarise(average = mean(Work.load.Average.day)) %>% 
  ggplot(aes(x = Age, y =  average)) +
  geom_point(aes(color = Age)) +
  geom_smooth(se = FALSE, color = "green", method = 'loess', formula = 'y ~ x') +
  scale_x_continuous(breaks = seq(27, 57, by = 5)) +
  labs(x = "age of worker",
       y = "average amount of workload in a day",
       title = "How much workload a worker receives as he/she ages",
       subtitle = "the older, the fewer work?") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(plot.subtitle = element_text(hjust = 0.5)) + 
  geom_vline(xintercept = 42, color = "red", linetype = "dotted", size = 0.6)

ggsave("age_workload.pdf")
```
